version: "3.9"
name: "example"
services:

  nginx-php-fpm:
    image: akeb/nginx-php-fpm:${PHP_VERSION}
    hostname: ${DOMAIN_NAME}
    volumes:
      - ../:/app/:rw
      - ./logs/nginx/:/var/log/nginx/:rw
      - ./logs/php/:/var/log/php/:rw
      - ./hosts.sh:/usr/local/etc/hosts.sh
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
