version: "3.9"
name: "example"
services:

  php-fpm:
    image: babadzhanyan/php-fpm:8.3
    volumes:
      - ../:/var/www/html/:rw
      - ./logs/php.log:/var/log/fpm-php.www.log:rw
      - ./hosts.sh:/usr/local/etc/hosts.sh

  nginx:
    image: babadzhanyan/nginx:latest
    hostname: my.example.ru
    volumes:
      - ../:/var/www/html/:rw
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/:/var/log/nginx/:rw
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php-fpm
    links:
      - php-fpm
