version: "3.9"
name: "example"
services:

  php-fpm:
    image: babadzhanyan/php-fpm:${PHP_VERSION}
    volumes:
      - ../:/var/www/html/:rw
      - ./logs/php.log:/var/log/php/php-fpm.log:rw
      - ./hosts.sh:/usr/local/etc/hosts.sh

  nginx:
    image: babadzhanyan/nginx:latest
    hostname: ${DOMAIN_NAME}
    volumes:
      - ../:/var/www/html/:rw
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/:/var/log/nginx/:rw
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
    depends_on:
      - php-fpm
    links:
      - php-fpm
