name: build nginx-php-fpm

on:
  push:
    # branches: main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
        system: ['nginx-php-fpm', 'php-fpm']
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Copy root certificate
      run: echo "${{ secrets.ROOT_CRT }}" > ./${{ matrix.system }}/root_ca.crt

    - name: build the image
      run: |
        docker buildx build \
        --build-arg PHP_VERSION=${{ matrix.version }} \
        --push \
        --tag akeb/${{ matrix.system }}:${{ matrix.version }} \
        --platform linux/amd64,linux/arm/v7,linux/arm64/v8 \
        ./${{ matrix.system }}/
